### ISSUE TITLE
How to add a custom partitioner

### ISSUE THREAD

**Issue by abhisheksahani** [confluentinc/kafka-connect-storage-common#107]
We have created a custom partitioner whose behaviour is same as FieldPartitioner but we are passing the timestamp field from which we are deriving current year,month,date and hour and adding it to partition fields. for this we extend the current existing FieldPartitioner and added changes . Now on pointing partitioner.class to our new extended FieldPartitioner we are getting null pointer exception. can someone explain how to add custome partitioner.

**Comment by abhisheksahani** [comment]
stack trace :
 at io.confluent.connect.storage.partitioner.PartitionerConfig.classNameEquals(PartitionerConfig.java:269)
        at io.confluent.connect.storage.partitioner.PartitionerConfig.access$000(PartitionerConfig.java:32)
        at io.confluent.connect.storage.partitioner.PartitionerConfig$PartitionerClassDependentsRecommender.visible(PartitionerConfig.java:237)
        at org.apache.kafka.common.config.ConfigDef.validate(ConfigDef.java:611)
        at org.apache.kafka.common.config.ConfigDef.validate(ConfigDef.java:619)
        at org.apache.kafka.common.config.ConfigDef.validate(ConfigDef.java:527)
        at org.apache.kafka.common.config.ConfigDef.validateAll(ConfigDef.java:510)
        at org.apache.kafka.common.config.ConfigDef.validate(ConfigDef.java:492)
        at org.apache.kafka.connect.connector.Connector.validate(Connector.java:135)
        at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:282)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$6.call(DistributedHerder.java:537)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$6.call(DistributedHerder.java:534)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:270)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by jkondapalli03** [comment]
@abhisheksahani - were you able to solve this problem? I'm seeing similar issue with my custom partitioner as well. any pointers to the solution are much appreciated!

**Comment by abhisheksahani** [comment]
@jkondapalli03  yes we were able to solve this , just take the pull of kafka-connect-storage-partitioner and add your custom class which extends extends DefaultPartitioner<T> and build it .For example we are using confluent-5.2.2,so copy the jar to location confluent-5.2.2/share/java/kafka-connect-hdfs/ (make sure you add this confluent-5.2.2/share/java/ directory path to plugin.path).
we are using connect-avro-distributed.properties file to set this property (plugin.path=/confluent-5.2.2/share/java)
and later run the service with following command
sudo ./connect-distributed ../etc/schema-registry/connect-avro-distributed.properties

**Comment by jkondapalli03** [comment]
I will try the solution you mentioned as well but, I copied the jar to `/usr/share/java/kafka-connect-storage-common/.` to get rid of NPE

**Comment by abhisheksahani** [comment]
it will load the jars from all subdirectory under /usr/share/java , above location (/usr/share/java/kafka-connect-storage-common/) should also work.
