### ISSUE TITLE
TimestampExtractor fails to extract timestamp with RecordField from a protobuf event

### ISSUE THREAD

**Issue by bagipriyank** [confluentinc/kafka-connect-storage-common#120]
Event Schema
```
syntax = "proto3";

import "google/protobuf/wrappers.proto";

option java_package = "com.bagi.protobuf";
option java_outer_classname = "TrackingEvent";

/**
 * single tracking event
*/
message Event {
    string build = 1; // build
    uint64 event_ts = 2; // epoch seconds at the time of event
    string user_id = 3; // user id
    EventType eventType = 4; // event type

    enum EventType {
            UNKNOWN = 0; // the default value
            IMPRESSION = 1;
            CLICK = 2;
            PLAY = 3;
    }

    google.protobuf.Int32Value vertical_index = 5; // vertical index on the grid
    google.protobuf.Int32Value horizontal_index = 6; // horizontal index on the grid
}
```

I am using kafka-connector-s3 to sink events to s3 bucket. Here is worker.properties
```
bootstrap.servers = localhost:9092
key.converter = org.apache.kafka.connect.storage.StringConverter
value.converter = com.blueapron.connect.protobuf.ProtobufConverter
value.converter.protoClassName = com.bagi.protobuf.TrackingEvent$Event
plugin.path = /usr/local/share/java/
offset.storage.file.filename = /etc/kafka-offsets
```

and s3-sink.properties
```
name=s3-sink
connector.class=io.confluent.connect.s3.S3SinkConnector

tasks.max=1
topics=PLAY

format.class=io.confluent.connect.s3.format.parquet.ParquetFormat
flush.size=100000
rotate.interval.ms=900000

s3.region=us-east-1
s3.bucket.name=dev-bagi
s3.part.size=5242880

storage.class=io.confluent.connect.s3.storage.S3Storage
file.delim=_

partitioner.class=io.confluent.connect.storage.partitioner.TimeBasedPartitioner
partition.duration.ms=900000
path.format='dt'=YYYY-MM-dd
locale=en-US
timezone=UTC
timestamp.extractor=RecordField
timestamp.field=event_ts

schema.compatibility=NONE
```

Stacktrace from logs
```
[2020-01-24 13:24:20,469] ERROR Unsupported type 'bytes' for user-defined timestamp field. (io.confluent.connect.storage.partitioner.TimeBasedPartitioner:295)
[2020-01-24 13:24:20,469] ERROR WorkerSinkTask{id=s3-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask:559)
io.confluent.connect.storage.errors.PartitionException: Error extracting timestamp from record field: event_ts
	at io.confluent.connect.storage.partitioner.TimeBasedPartitioner$RecordFieldTimestampExtractor.extract(TimeBasedPartitioner.java:299)
	at io.confluent.connect.storage.partitioner.TimestampExtractor.extract(TimestampExtractor.java:41)
	at io.confluent.connect.s3.TopicPartitionWriter.executeState(TopicPartitionWriter.java:206)
	at io.confluent.connect.s3.TopicPartitionWriter.write(TopicPartitionWriter.java:188)
	at io.confluent.connect.s3.S3SinkTask.put(S3SinkTask.java:190)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:539)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Is using `uint64` for event_ts in protocol buffer schema the reason for this failure?

**Comment by bagipriyank** [comment]
I think the issue is happening because `com.blueapron.connect.protobuf.ProtobufConverter` is treating `uint64` protobuf field as `Decimal`. Reference: https://github.com/blueapron/kafka-connect-protobuf-converter/blob/master/src/main/java/com/blueapron/connect/protobuf/ProtobufData.java#L147

But shouldn't a decimal also be treated as a number and not bytes?

**Comment by bagipriyank** [comment]
> I think the issue is happening because `com.blueapron.connect.protobuf.ProtobufConverter` is treating `uint64` protobuf field as `Decimal`. Reference: https://github.com/blueapron/kafka-connect-protobuf-converter/blob/master/src/main/java/com/blueapron/connect/protobuf/ProtobufData.java#L147
> 
> But shouldn't a decimal also be treated as a number and not bytes?

https://github.com/blueapron/kafka-connect-protobuf-converter/issues/28#issuecomment-578381486 clarifies why `uint64` in protocol buffer is mapped to `Decimal` - `bytes` in kafka connect schema. I'll try changing to type of `event_ts` to `int64`.

**Comment by bagipriyank** [comment]
I tried using `int64` instead of `uint64` but now the partition value is always `dt=1970-01-19` even when `event_ts = 1579996647` which corresponds to `Saturday, January 25, 2020 11:57:27 PM UTC`

**Comment by bagipriyank** [comment]
> I tried using `int64` instead of `uint64` but now the partition value is always `dt=1970-01-19` even when `event_ts = 1579996647` which corresponds to `Saturday, January 25, 2020 11:57:27 PM UTC`

this is happening because i am passing in epoch seconds. every thing works fine if i used epoch in milliseconds instead.
