### ISSUE TITLE
[Question]: S3 Sink Connector

### ISSUE THREAD

**Issue by amit-c1x** [confluentinc/kafka-connect-storage-common#34]
Hi,

I am using s3 sink connector with the relevant config defined as follows:

```
	
	"storage.class": "io.confluent.connect.s3.storage.S3Storage",
	"format.class": "io.confluent.connect.s3.format.json.JsonFormat",
	"key.converter": "org.apache.kafka.connect.storage.StringConverter",
	"value.converter": "org.apache.kafka.connect.storage.StringConverter",
	
	"key.converter.schemas.enable": "false",
	"value.converter.schemas.enable": "false",
	
	"schema.generator.class": "io.confluent.connect.storage.hive.schema.DefaultSchemaGenerator",
	
	"partitioner.class": "io.confluent.connect.storage.partitioner.HourlyPartitioner",
	"partition.duration.ms": 3600000,
	"timestamp.extractor": "RecordField",
	"timestamp.field": "timestamp",
	"locale": "en",
	"timezone": "UTC",
```

However, the sink task throws the following exception:

```
[2017-09-15 02:40:05,830] ERROR Task s3-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerSinkTask:455)
io.confluent.connect.storage.errors.PartitionException: Error encoding partition.
        at io.confluent.connect.storage.partitioner.TimeBasedPartitioner$RecordFieldTimestampExtractor.extract(TimeBasedPartitioner.java:289)
        at io.confluent.connect.s3.TopicPartitionWriter.write(TopicPartitionWriter.java:174)
        at io.confluent.connect.s3.S3SinkTask.put(S3SinkTask.java:180)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:435)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:251)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:180)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

The kafka messages are in JSON format and there is a field named timestamp which holds the epochtime of the event.

Could someone help me figure out the issue?

Thanks in Advance!!

**Comment by cricket007** [comment]
This should be fixed by 11aec9382885d99c4d8bc220fbbfc4340b220495 . Confluent 3.2.2, and newer
