### ISSUE TITLE
Add ability to write multiple topics into single output path

### ISSUE THREAD

**Issue by OneCricketeer** [confluentinc/kafka-connect-storage-common#91]
> [_From StackOverflow_](https://stackoverflow.com/q/53329362/2308683)

Naturally, one might try to use `RegexRouter` to send multiple topics to a single directory. Say, data coming from JDBC Source connector

```json
    "topics": "SQLSERVER-TEST-TABLE_TEST",

    "transforms":"dropPrefix",      
    "transforms.dropPrefix.type":"org.apache.kafka.connect.transforms.RegexRouter",  
    "transforms.dropPrefix.regex":"SQLSERVER-TEST-(.*)",  
    "transforms.dropPrefix.replacement":"$1"
```

But this will throw a NPE

```java
Caused by: java.lang.NullPointerException
    at io.confluent.connect.s3.S3SinkTask.put(S3SinkTask.java:188)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:564)
    ... 10 more
```

And if debugging (the S3 Connector, specifically), we see that the data that's needed to generate the top level folder is available, but the storage writer cannot access it from the map.  

There is a HashMap with the original topic name (`SQLSERVER_TEST_TABLE_TEST-0`), and the transform has already been applied (`TABLE-TEST-0`), so if we lookup the "new" topicname, it cannot find the S3 writer for the `TopicPartition`.

![image](https://user-images.githubusercontent.com/1930631/49358652-063eac80-f699-11e8-87d8-9ad42a736575.png)

I think adding a separate config in the `storage-common` module for performing the logic of the `RegexRouter` outside of the SMT pipeline will help solve this problem, and can be patched into the Hadoop, S3, and other storage connectors

**Comment by dongxiaohe** [comment]
Will do, I run those whole thing by using docker directly and EKS (kubernetes). Now I need to compile the project and set up the local environment, it may take some time 😄

**Comment by cricket007** [comment]
I've been filling in working example stacks here over time - https://github.com/cricket007/kafka-connect-sandbox
